[package]
name = "builder"
version = "0.1.0"
edition = "2021"

[dependencies]
convert_case = "0.6.0"
once_cell = "1.18.0"
readonly = "0.2.10"
regex = "1.9.1"
serde = { version = "1.0.166", features = ["derive"] }
serde_json = "1.0.100"

[features]
debug = []
default = ["debug"]